name: Build and Deploy to Cloud Run

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: uniua-425415
  GAR_LOCATION: europe-central2
  SERVICE_FRONTEND: uniua-front
  SERVICE_BACKEND: uniua-back
  REGION: europe-central2
  REPO: uniua

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push FrontEnd Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-frontend:${{ github.sha }}" ./front-end
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-frontend:${{ github.sha }}"
          
      - name: Build and Push BackEnd Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-backend:${{ github.sha }}" ./back-end
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-backend:${{ github.sha }}"

      - name: Deploy FrontEnd to Cloud Run
        id: deploy_frontend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_FRONTEND }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-frontend:${{ github.sha }}

      - name: Deploy BackEnd to Cloud Run
        id: deploy_backend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_BACKEND }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/uniua-backend:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
